<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLmgK34E\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLmgK34E/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLmgK34E.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLmgK34E\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLmgK34E\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LmgK34E',
    'container.build_id' => '9f161c17',
    'container.build_time' => 1617733233,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLmgK34E');
